# permissions for end users to edit filebeatconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: filebeatconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: filebeat-operator
    app.kubernetes.io/part-of: filebeat-operator
    app.kubernetes.io/managed-by: kustomize
  name: filebeatconfig-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - filebeatconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - filebeatconfigs/status
  verbs:
  - get
